config/routes.rb
Cine::Application.routes.draw do
  get "static_pages/home"

  get "welcome/index"
resources:apps

  root :to => 'welcome#index'

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :actor, :actress, :average_vote, :cc1, :cc2, :cc3, :cc4, :comedian, :director, :director, :language, :movie_image, :movie_name, :music, :picture, :reaction_gif, :release_date, :release_month, :release_year, :vote
end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
  attr_accessible :Actor, :Actress, :Average_Vote, :Director, :Language, :Movie_Image, :Movie_Name, :Picture, :Reaction_Gif, :Release_Month, :Release_Year, :Vote, :cc1, :cc2, :cc3, :cc4, :comedian
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_name %><br />
    <%= f.text_field :movie_name %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :actor %><br />
    <%= f.text_field :actor %>
  </div>
  <div class="field">
    <%= f.label :actress %><br />
    <%= f.text_field :actress %>
  </div>
  <div class="field">
    <%= f.label :comedian %><br />
    <%= f.text_field :comedian %>
  </div>
  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :music %><br />
    <%= f.text_field :music %>
  </div>
  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :release_year %><br />
    <%= f.number_field :release_year %>
  </div>
  <div class="field">
    <%= f.label :release_month %><br />
    <%= f.number_field :release_month %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br />
    <%= f.date_select :release_date %>
  </div>
  <div class="field">
    <%= f.label :vote %><br />
    <%= f.number_field :vote %>
  </div>
  <div class="field">
    <%= f.label :average_vote %><br />
    <%= f.text_field :average_vote %>
  </div>
  <div class="field">
    <%= f.label :movie_image %><br />
    <%= f.text_field :movie_image %>
  </div>
  <div class="field">
    <%= f.label :reaction_gif %><br />
    <%= f.text_field :reaction_gif %>
  </div>
  <div class="field">
    <%= f.label :cc1 %><br />
    <%= f.text_field :cc1 %>
  </div>
  <div class="field">
    <%= f.label :cc2 %><br />
    <%= f.text_field :cc2 %>
  </div>
  <div class="field">
    <%= f.label :cc3 %><br />
    <%= f.text_field :cc3 %>
  </div>
  <div class="field">
    <%= f.label :cc4 %><br />
    <%= f.text_field :cc4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>Movie name</th>
    <th>Language</th>
    <th>Picture</th>
    <th>Actor</th>
    <th>Actress</th>
    <th>Comedian</th>
    <th>Director</th>
    <th>Music</th>
    <th>Director</th>
    <th>Release year</th>
    <th>Release month</th><br>
    <th>Release date</th>
    <th>Vote</th>
    <th>Average vote</th>
    <th>Movie image</th>
    <th>Reaction gif</th>
    <th>Cc1</th>
    <th>Cc2</th>
    <th>Cc3</th>
    <th>Cc4</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.movie_name %></td>
    <td><%= app.language %></td>
    <td><%= app.picture %></td>
    <td><%= app.actor %></td>
    <td><%= app.actress %></td>
    <td><%= app.comedian %></td>
    <td><%= app.director %></td>
    <td><%= app.music %></td>
    <td><%= app.director %></td>
    <td><%= app.release_year %></td><br>
    <td><%= app.release_month %></td>
    <td><%= app.release_date %></td>
    <td><%= app.vote %></td>
    <td><%= app.average_vote %></td>
    <td><%= app.movie_image %></td>
    <td><%= app.reaction_gif %></td>
    <td><%= app.cc1 %></td>
    <td><%= app.cc2 %></td>
    <td><%= app.cc3 %></td>
    <td><%= app.cc4 %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Movie name:</b>
  <%= @app.movie_name %>
</p>

<p>
  <b>Language:</b>
  <%= @app.language %>
</p>

<p>
  <b>Picture:</b>
  <%= @app.picture %>
</p>

<p>
  <b>Actor:</b>
  <%= @app.actor %>
</p>

<p>
  <b>Actress:</b>
  <%= @app.actress %>
</p>

<p>
  <b>Comedian:</b>
  <%= @app.comedian %>
</p>

<p>
  <b>Director:</b>
  <%= @app.director %>
</p>

<p>
  <b>Music:</b>
  <%= @app.music %>
</p>

<p>
  <b>Director:</b>
  <%= @app.director %>
</p>

<p>
  <b>Release year:</b>
  <%= @app.release_year %>
</p>

<p>
  <b>Release month:</b>
  <%= @app.release_month %>
</p>

<p>
  <b>Release date:</b>
  <%= @app.release_date %>
</p>

<p>
  <b>Vote:</b>
  <%= @app.vote %>
</p>

<p>
  <b>Average vote:</b>
  <%= @app.average_vote %>
</p>

<p>
  <b>Movie image:</b>
  <%= @app.movie_image %>
</p>

<p>
  <b>Reaction gif:</b>
  <%= @app.reaction_gif %>
</p>

<p>
  <b>Cc1:</b>
  <%= @app.cc1 %>
</p>

<p>
  <b>Cc2:</b>
  <%= @app.cc2 %>
</p>

<p>
  <b>Cc3:</b>
  <%= @app.cc3 %>
</p>

<p>
  <b>Cc4:</b>
  <%= @app.cc4 %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cine</title>
   
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
  </head>
<body>

 <%=yield%>
</body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/welcome/index.html.erb
<h1>CiNE APPPLICATION</h1>
<p>Find me in app/views/welcome/index.html.erb</p>